Repository hypervel/components, pull requests merged in 2025-05, with the labels that each got.

#72 improve: support starting web server without .env file
  src/foundation/src/Listeners/ReloadDotenvAndConfig.php
Labels: enhancement

#75 improve: add missing paths functions
  src/foundation/src/Application.php
  src/foundation/src/Contracts/Application.php
  src/foundation/src/helpers.php
Labels: enhancement

#76 feature: implement new translation package
  composer.json
  src/foundation/src/Application.php
  src/foundation/src/helpers.php
  src/support/src/Facades/Lang.php
  src/support/src/NamespacedItemResolver.php
  src/support/src/Traits/Macroable.php
  src/testbench/src/ConfigProviderRegister.php
  src/translation/LICENSE.md
  src/translation/README.md
  src/translation/composer.json
  src/translation/lang/en/validation.php
  src/translation/src/ArrayLoader.php
  src/translation/src/ConfigProvider.php
  src/translation/src/Contracts/HasLocalePreference.php
  src/translation/src/Contracts/Loader.php
  src/translation/src/Contracts/Translator.php
  src/translation/src/CreatesPotentiallyTranslatedStrings.php
  src/translation/src/FileLoader.php
  src/translation/src/Functions.php
  src/translation/src/LoaderFactory.php
  src/translation/src/MessageSelector.php
  src/translation/src/PotentiallyTranslatedString.php
  src/translation/src/Translator.php
  src/translation/src/TranslatorFactory.php
  tests/Container/ContainerCallTest.php
  tests/Foundation/FoundationApplicationTest.php
  tests/Translation/TranslationFileLoaderTest.php
  tests/Translation/TranslationMessageSelectorTest.php
  tests/Translation/TranslationTranslatorTest.php
Labels: feature

#80 fix: support nested uploaded files in http kernel
  src/foundation/src/Http/Kernel.php
Labels: bug

#81 improve: improve error message when request context is not set
  src/http/src/Request.php
  tests/Http/RequestTest.php
Labels: enhancement

#79 improve: improve component consistency
  src/auth/src/Access/GateFactory.php
  src/auth/src/AuthManager.php
  src/auth/src/ConfigProvider.php
  src/auth/src/Contracts/Factory.php
  src/auth/src/Functions.php
  src/auth/src/UserResolver.php
  src/devtool/src/Commands/EventListCommand.php
  src/event/src/Contracts/Dispatcher.php
  src/event/src/Contracts/ListenerProvider.php
  src/event/src/EventDispatcher.php
  src/event/src/ListenerProvider.php
  src/foundation/src/Application.php
  src/foundation/src/Providers/FoundationServiceProvider.php
  src/foundation/src/Testing/Concerns/InteractsWithAuthentication.php
  src/support/src/Contracts/Arrayable.php
  src/support/src/Contracts/Htmlable.php
  src/support/src/Contracts/Jsonable.php
  src/support/src/Contracts/MessageBag.php
  src/support/src/Contracts/MessageProvider.php
  src/support/src/HigherOrderWhenProxy.php
  src/support/src/MessageBag.php
  src/support/src/Traits/Conditionable.php
  tests/Event/Hyperf/EventDispatcherTest.php
  tests/Foundation/Testing/Concerns/InteractsWithAuthenticationTest.php
  tests/Mail/MailMailerTest.php
Labels: enhancement

#85 improve: make Hypervel's translation compatible with Hyperf's translation
  src/foundation/src/Application.php
  src/translation/composer.json
  src/translation/src/Contracts/Loader.php
  src/translation/src/Contracts/Translator.php
  src/translation/src/Translator.php
Labels: enhancement

#93 fix: fix incoherent behavior in exception handler
  src/foundation/src/ConfigProvider.php
  src/foundation/src/Exceptions/Handlers/HttpExceptionHandler.php
  src/foundation/src/Http/Kernel.php
  src/testbench/src/TestCase.php
Labels: bug

#95 fix: fix facade accessor of session
  src/support/src/Facades/Session.php
Labels: bug

#96 fix: pass middleware parameters in aliased middleware
  src/foundation/src/Http/Traits/HasMiddleware.php
  tests/Foundation/Http/KernelTest.php
Labels: bug

#97 feat: add make:middleware command
  src/devtool/src/ConfigProvider.php
  src/devtool/src/Generator/MiddlewareCommand.php
  src/devtool/src/Generator/stubs/Middleware.stub
  src/devtool/src/Generator/stubs/middleware.psr15.stub
  src/devtool/src/Generator/stubs/middleware.stub
Labels: enhancement

#94 improve: be compatible with different default value of zscan in new redis version
  src/cache/src/RedisTagSet.php
  src/cache/src/RedisTaggedCache.php
  src/cache/src/RedisTaggedCacheChunkedEntries.php
  tests/Cache/CacheRedisTaggedCacheTest.php
Labels: enhancement

#106 improve: support assiginging proxy class in createPoolProxy function
  src/object-pool/src/Traits/HasPoolProxy.php
Labels: enhancement

#107 fix: fix ValidatorFactory to resolve DatabasePresenceVerifier
  src/validation/src/ValidatorFactory.php
Labels: bug

#103 feat: add `has` method in route collector
  src/router/src/RouteCollector.php
  src/support/src/Facades/Route.php
  tests/Router/RouteCollectorTest.php
Labels: feature

#108 feat: enhance Request::all() method with selective field filtering
  src/foundation/src/Http/FormRequest.php
  src/http/src/Request.php
  tests/Http/RequestTest.php
Labels: enhancement

#110 improve: extract default aliases to facade class
  src/foundation/publish/app.php
  src/support/src/Facades/Facade.php
  src/testbench/workbench/config/app.php
Labels: enhancement
