Repository hypervel/components, pull requests merged in 2025-06, with the labels that each got.

#112 improve: improve default connection in RedisBroadcaster
  src/broadcasting/src/BroadcastManager.php
  src/broadcasting/src/Broadcasters/RedisBroadcaster.php
  src/broadcasting/src/Contracts/ShouldBroadcast.php
Labels: enhancement

#119 fix: fix nonce in redirect function in AbstractProvider
  src/socialite/src/Two/AbstractProvider.php
  src/socialite/src/Two/BitbucketProvider.php
  src/socialite/src/Two/FacebookProvider.php
  src/socialite/src/Two/GithubProvider.php
  src/socialite/src/Two/GitlabProvider.php
  src/socialite/src/Two/GoogleProvider.php
  src/socialite/src/Two/LinkedInOpenIdProvider.php
  src/socialite/src/Two/LinkedInProvider.php
  src/socialite/src/Two/OpenIdProvider.php
  src/socialite/src/Two/SlackOpenIdProvider.php
  src/socialite/src/Two/SlackProvider.php
  src/socialite/src/Two/TwitchProvider.php
  src/socialite/src/Two/XProvider.php
  tests/Socialite/Fixtures/GoogleTestProviderStub.php
  tests/Socialite/Fixtures/OAuthTwoTestProviderStub.php
  tests/Socialite/Fixtures/OpenIdTestProviderStub.php
  tests/Socialite/OpenIdProviderTest.php
Labels: bug

#118 fix: fix getRootUrl in url generator for non-greedy search
  src/router/src/UrlGenerator.php
Labels: bug

#123 feat: enhance make:model command
  src/devtool/src/Generator/FactoryCommand.php
  src/devtool/src/Generator/ModelCommand.php
  src/devtool/src/Generator/stubs/policy.stub
Labels: enhancement

#128 feat: implement api-client package
  composer.json
  src/api-client/LICENSE.md
  src/api-client/README.md
  src/api-client/composer.json
  src/api-client/src/ApiClient.php
  src/api-client/src/ApiRequest.php
  src/api-client/src/ApiResource.php
  src/api-client/src/ApiResponse.php
  src/api-client/src/PendingRequest.php
  src/api-client/src/RequestMiddleware.php
  src/api-client/src/ResponseMiddleware.php
  tests/ApiClient/ApiClientTest.php
  tests/ApiClient/ApiRequestTest.php
  tests/ApiClient/ApiResourceTest.php
Labels: feature

#129 fix: fix cron scheduler for non-second level interval
  src/console/src/Commands/ScheduleRunCommand.php
  src/console/src/Scheduling/Event.php
Labels: bug
