Repository hypervel/components, pull requests merged in 2025-07, with the labels that each got.

#131 fix: initialize dispatcher property to prevent access before initialization error
  src/console/src/Scheduling/Schedule.php
Labels: bug

#136 feat: add SoftDeletes trait
  src/core/src/Database/Eloquent/SoftDeletes.php
Labels: feature

#132 fix: correct the file path of `make:test` command
  src/devtool/src/Generator/TestCommand.php
Labels: bug

#147 fix: fix phpdoc of cache facade
  src/cache/src/CacheManager.php
  src/support/src/Facades/Cache.php
Labels: enhancement

#149 feat: add make:exception command
  src/devtool/src/ConfigProvider.php
  src/devtool/src/Generator/ExceptionCommand.php
  src/devtool/src/Generator/stubs/exception-render-report.stub
  src/devtool/src/Generator/stubs/exception-render.stub
  src/devtool/src/Generator/stubs/exception-report.stub
  src/devtool/src/Generator/stubs/exception.stub
Labels: feature

#148 feature: migrate spatie/laravel-permission package
  LICENSE.md
  composer.json
  src/permission/LICENSE.md
  src/permission/README.md
  src/permission/composer.json
  src/permission/database/migrations/2025_07_02_000000_create_permission_tables.php
  src/permission/publish/permission.php
  src/permission/src/ConfigProvider.php
  src/permission/src/Console/ShowCommand.php
  src/permission/src/Contracts/Factory.php
  src/permission/src/Contracts/Permission.php
  src/permission/src/Contracts/Role.php
  src/permission/src/Exceptions/PermissionException.php
  src/permission/src/Exceptions/RoleException.php
  src/permission/src/Exceptions/UnauthorizedException.php
  src/permission/src/Middlewares/PermissionMiddleware.php
  src/permission/src/Middlewares/RoleMiddleware.php
  src/permission/src/Models/Permission.php
  src/permission/src/Models/Role.php
  src/permission/src/PermissionManager.php
  src/permission/src/PermissionServiceProvider.php
  src/permission/src/Traits/HasPermission.php
  src/permission/src/Traits/HasRole.php
  tests/Permission/Enums/Permission.php
  tests/Permission/Enums/Role.php
  tests/Permission/HasPermissionTest.php
  tests/Permission/HasRoleTest.php
  tests/Permission/Middlewares/PermissionMiddlewareTest.php
  tests/Permission/Middlewares/RoleMiddlewareTest.php
  tests/Permission/Models/User.php
  tests/Permission/PermissionManagerTest.php
  tests/Permission/PermissionTestCase.php
  tests/Permission/migrations/2025_07_01_000000_create_users_table.php
Labels: feature

#158 fix: add PHPDoc for HasNode trait in permission package
  src/nested-set/src/HasNode.php
Labels: enhancement

#162 fix: fix wrong array manipulation of load commands in kernel
  src/foundation/src/Console/Kernel.php
Labels: bug

#165 fix: fix permission config and migrations
  src/permission/src/ConfigProvider.php
  src/permission/src/PermissionManager.php
Labels: bug

#166 refactor: add forbidden permission middleware and sync
  src/permission/src/Middlewares/PermissionMiddleware.php
  src/permission/src/Middlewares/RoleMiddleware.php
  src/permission/src/Traits/HasPermission.php
  tests/Permission/HasPermissionTest.php
  tests/Permission/Middlewares/PermissionMiddlewareTest.php
  tests/Permission/Middlewares/RoleMiddlewareTest.php
Labels: breaking-change

#171 feat: add extra methods to request
  src/http/src/Contracts/RequestContract.php
  src/http/src/Request.php
  src/support/src/Facades/Request.php
  tests/Http/RequestTest.php
Labels: feature

#172 feat: add afterErrorResponse function for exception handler
  src/foundation/src/Exceptions/Contracts/ExceptionHandler.php
  src/foundation/src/Exceptions/Handler.php
  src/http/LICENSE.md
  tests/Foundation/FoundationExceptionHandlerTest.php
Labels: feature

#173 feat: support options method in http test client
  src/foundation/src/Testing/Concerns/MakesHttpRequests.php
  src/foundation/src/Testing/Http/TestClient.php
Labels: enhancement

#174 feat: support cors in http
  src/foundation/src/Testing/Concerns/MakesHttpRequests.php
  src/http/src/CoreMiddleware.php
  src/http/src/Cors.php
  src/http/src/Exceptions/InvalidOptionException.php
  src/http/src/Middleware/HandleCors.php
  src/router/src/RouteCollector.php
  src/testbench/workbench/config/cors.php
  tests/Http/CorsTest.php
  tests/Http/Middleware/HandleCorsTest.php
Labels: feature

#150 feat: add Sanctum component
  composer.json
  src/auth/publish/auth.php
  src/sanctum/LICENSE.md
  src/sanctum/README.md
  src/sanctum/composer.json
  src/sanctum/database/migrations/2023_08_03_000000_create_personal_access_tokens_table.php
  src/sanctum/publish/sanctum.php
  src/sanctum/routes/web.php
  src/sanctum/src/Console/Commands/PruneExpired.php
  src/sanctum/src/Contracts/HasAbilities.php
  src/sanctum/src/Contracts/HasApiTokens.php
  src/sanctum/src/Events/TokenAuthenticated.php
  src/sanctum/src/Exceptions/MissingAbilityException.php
  src/sanctum/src/HasApiTokens.php
  src/sanctum/src/Http/Controllers/CsrfCookieController.php
  src/sanctum/src/Http/Middleware/AuthenticateSession.php
  src/sanctum/src/Http/Middleware/CheckAbilities.php
  src/sanctum/src/Http/Middleware/CheckForAnyAbility.php
  src/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php
  src/sanctum/src/NewAccessToken.php
  src/sanctum/src/PersonalAccessToken.php
  src/sanctum/src/Sanctum.php
  src/sanctum/src/SanctumGuard.php
  src/sanctum/src/SanctumServiceProvider.php
  src/sanctum/src/TransientToken.php
  tests/Sanctum/ActingAsTest.php
  tests/Sanctum/AuthenticateRequestsTest.php
  tests/Sanctum/CheckAbilitiesTest.php
  tests/Sanctum/CheckForAnyAbilityTest.php
  tests/Sanctum/CurrentApplicationUrlWithPortTest.php
  tests/Sanctum/EnsureFrontendRequestsAreStatefulTest.php
  tests/Sanctum/FrontendRequestsAreStatefulTest.php
  tests/Sanctum/GuardTest.php
  tests/Sanctum/HasApiTokensTest.php
  tests/Sanctum/MissingAbilityExceptionTest.php
  tests/Sanctum/NewAccessTokenTest.php
  tests/Sanctum/PersonalAccessTokenTest.php
  tests/Sanctum/PruneExpiredTest.php
  tests/Sanctum/SimpleGuardTest.php
  tests/Sanctum/Stub/EloquentUserProvider.php
  tests/Sanctum/Stub/TestUser.php
  tests/Sanctum/Stub/User.php
  tests/Sanctum/Stub/UserWithApiTokens.php
  tests/Sanctum/TransientTokenTest.php
  tests/Sanctum/migrations/2023_08_03_000000_create_personal_access_tokens_table.php
Labels: feature

#177 feat: implement redis package
  composer.json
  src/core/src/ConfigProvider.php
  src/core/src/Redis/Redis.php
  src/core/src/Redis/RedisConnection.php
  src/core/src/Redis/RedisProxy.php
  src/redis/LICENSE.md
  src/redis/README.md
  src/redis/composer.json
  src/redis/src/ConfigProvider.php
  src/redis/src/Limiters/DurationLimiter.php
  src/redis/src/Limiters/LimiterTimeoutException.php
  src/redis/src/Redis.php
  src/redis/src/RedisConnection.php
  src/redis/src/RedisFactory.php
  src/redis/src/RedisPool.php
  src/redis/src/RedisProxy.php
  src/support/src/Facades/Redis.php
  src/testbench/src/ConfigProviderRegister.php
  tests/Redis/RedisConnectionTest.php
  tests/Redis/Stubs/RedisConnectionStub.php
Labels: feature

#178 feat: implement support uri
  composer.json
  src/http/src/Contracts/RequestContract.php
  src/http/src/Request.php
  src/support/composer.json
  src/support/src/Facades/Request.php
  src/support/src/Uri.php
  src/support/src/UriQueryString.php
  src/support/src/ValidatedInput.php
  tests/Http/RequestTest.php
  tests/Support/SupportUriTest.php
Labels: feature
