Repository hypervel/components, pull requests merged in 2025-08, with the labels that each got.

#130 Add context helper method similar to laravel.
  composer.json
  src/core/composer.json
  src/core/src/Context/Context.php
  src/core/src/helpers.php
  tests/Core/ContextTest.php
Labels: enhancement

#185 feat: add SetProcessTitle listener
  src/foundation/src/ConfigProvider.php
  src/foundation/src/Listeners/SetProcessTitle.php
Labels: enhancement

#187 feat: support deferred events
  src/event/src/EventDispatcher.php
  src/support/src/Facades/Event.php
  tests/Event/EventsDispatcherTest.php
Labels: feature

#192 chore: remove redis dependency in core and broadcasting
  src/broadcasting/composer.json
  src/core/composer.json
Labels: enhancement

#134 Adds the source file and line number to `dd()` output
  .php-cs-fixer.php
  src/foundation/src/Concerns/ResolvesDumpSource.php
  src/foundation/src/Console/CliDumper.php
  src/foundation/src/Http/HtmlDumper.php
  src/foundation/src/Providers/FoundationServiceProvider.php
  tests/Foundation/Console/CliDumperTest.php
  tests/Foundation/Http/HtmlDumperTest.php
  tests/Foundation/fixtures/fake-compiled-view-without-source-map.php
  tests/Foundation/fixtures/fake-compiled-view.php
Labels: enhancement

#201 improve: make service providers compatible with loading as config providers
  src/config/src/ProviderConfig.php
Labels: enhancement

#200 fix: fix `queue:work --once` command
  src/queue/src/Console/WorkCommand.php
Labels: bug

#179 feat: migrate the new version of the factory
  src/core/src/ConfigProvider.php
  src/core/src/Database/Eloquent/Factories/BelongsToManyRelationship.php
  src/core/src/Database/Eloquent/Factories/BelongsToRelationship.php
  src/core/src/Database/Eloquent/Factories/CrossJoinSequence.php
  src/core/src/Database/Eloquent/Factories/Factory.php
  src/core/src/Database/Eloquent/Factories/HasFactory.php
  src/core/src/Database/Eloquent/Factories/LegacyFactory.php
  src/core/src/Database/Eloquent/Factories/LegacyFactoryInvoker.php
  src/core/src/Database/Eloquent/Factories/Relationship.php
  src/core/src/Database/Eloquent/Factories/Sequence.php
  src/devtool/src/Generator/FactoryCommand.php
  src/devtool/src/Generator/stubs/factory.stub
  tests/Core/Database/Eloquent/Factories/FactoryTest.php
  tests/Core/Database/Eloquent/Factories/migrations/2025_07_24_000000_create_models.php
  tests/Core/Database/Fixtures/Factories/PriceFactory.php
  tests/Core/Database/Fixtures/Models/Price.php
Labels: feature

#113 refactor: improve seeder with namespace
  src/core/class_map/Database/Commands/Seeders/BaseCommand.php
  src/core/class_map/Database/Migrations/Migration.php
  src/core/src/ConfigProvider.php
  src/core/src/Database/Console/SeedCommand.php
  src/core/src/Database/Seeder.php
  src/devtool/src/Generator/stubs/seeder.stub
Labels: breaking-change

#191 feat: correct eloquent types
  composer.json
  phpstan.neon.dist
  phpstan.types.neon.dist
  src/core/src/Database/Eloquent/Builder.php
  src/core/src/Database/Eloquent/Collection.php
  src/core/src/Database/Eloquent/Concerns/HasRelationships.php
  src/core/src/Database/Eloquent/Concerns/QueriesRelationships.php
  src/core/src/Database/Eloquent/Factories/Factory.php
  src/core/src/Database/Eloquent/Model.php
  src/core/src/Database/Eloquent/ModelNotFoundException.php
  src/core/src/Database/Eloquent/Relations/BelongsTo.php
  src/core/src/Database/Eloquent/Relations/BelongsToMany.php
  src/core/src/Database/Eloquent/Relations/Concerns/WithoutAddConstraints.php
  src/core/src/Database/Eloquent/Relations/Contracts/Relation.php
  src/core/src/Database/Eloquent/Relations/HasMany.php
  src/core/src/Database/Eloquent/Relations/HasManyThrough.php
  src/core/src/Database/Eloquent/Relations/HasOne.php
  src/core/src/Database/Eloquent/Relations/HasOneThrough.php
  src/core/src/Database/Eloquent/Relations/MorphMany.php
  src/core/src/Database/Eloquent/Relations/MorphOne.php
  src/core/src/Database/Eloquent/Relations/MorphPivot.php
  src/core/src/Database/Eloquent/Relations/MorphTo.php
  src/core/src/Database/Eloquent/Relations/MorphToMany.php
  src/core/src/Database/Eloquent/Relations/Pivot.php
  src/core/src/Database/Eloquent/Relations/Relation.php
  src/core/src/Database/Eloquent/SoftDeletes.php
  src/core/src/Database/Query/Builder.php
  src/event/src/ListenerData.php
  src/permission/src/Traits/HasPermission.php
  src/support/src/Collection.php
  src/support/src/DataObject.php
  src/support/src/DateFactory.php
  src/support/src/Facades/DB.php
  src/support/src/Facades/Date.php
  src/support/src/HtmlString.php
  src/support/src/LazyCollection.php
  types/Autoload.php
  types/Database/Eloquent/Builder.php
  types/Database/Eloquent/Collection.php
  types/Database/Eloquent/Model.php
  types/Database/Eloquent/ModelNotFoundException.php
  types/Database/Eloquent/Relations.php
  types/Database/Query/Builder.php
Labels: enhancement
