Repository hypervel/components, pull requests merged in 2025-04, with the labels that each got.

#17 fix: fix version of phpunit to 10.5.45 to prevent from breaking change for runTest method
  composer.json
Labels: bug

#15 Feat: Implement `about` command
  src/console/src/CommandReplacer.php
  src/foundation/src/Application.php
  src/foundation/src/Bootstrap/RegisterFacades.php
  src/foundation/src/Bootstrap/RegisterProviders.php
  src/foundation/src/ClassLoader.php
  src/foundation/src/ConfigProvider.php
  src/foundation/src/Console/Commands/AboutCommand.php
  src/foundation/src/Contracts/Application.php
  src/support/src/Composer.php
  tests/Foundation/Bootstrap/RegisterFacadesTest.php
  tests/Foundation/Bootstrap/RegisterProvidersTest.php
Labels: feature

#14 Feat: Implement testbench package
  .gitignore
  composer.json
  src/container/src/ScanConfig.php
  src/filesystem/src/Filesystem.php
  src/foundation/src/ClassLoader.php
  src/foundation/src/Providers/FoundationServiceProvider.php
  src/foundation/src/Testing/Traits/CanConfigureMigrationCommands.php
  src/testbench/.gitignore
  src/testbench/bin/testbench-sync
  src/testbench/composer.json
  src/testbench/src/Bootstrapper.php
  src/testbench/src/ConfigProviderRegister.php
  src/testbench/src/TestCase.php
  src/testbench/testbench.yaml
  src/testbench/workbench/app/Console/Commands/DummyCommand.php
  src/testbench/workbench/app/Exceptions/ExceptionHandler.php
  src/testbench/workbench/app/Http/Controllers/ExampleController.php
  src/testbench/workbench/app/Models/User.php
  src/testbench/workbench/app/Providers/WorkbenchServiceProvider.php
  src/testbench/workbench/config/app.php
  src/testbench/workbench/config/auth.php
  src/testbench/workbench/config/database.php
  src/testbench/workbench/config/exceptions.php
  src/testbench/workbench/config/logging.php
  src/testbench/workbench/config/queue.php
  src/testbench/workbench/config/session.php
  src/testbench/workbench/database/factories/UserFactory.php
  src/testbench/workbench/database/migrations/2023_08_03_000000_create_users_table.php
  src/testbench/workbench/lang/en/welcome.php
  src/testbench/workbench/resources/views/welcome.blade.php
  src/testbench/workbench/routes/api.php
  src/testbench/workbench/routes/console.php
  src/testbench/workbench/routes/web.php
  tests/Bus/BusBatchTest.php
  tests/Console/ArtisanCommandTest.php
  tests/Core/EloquentBroadcastingTest.php
  tests/Foundation/Testing/ApplicationTestCase.php
  tests/Foundation/Testing/BootTraitsTest.php
  tests/Foundation/Testing/Concerns/InteractsWithAuthenticationTest.php
  tests/Foundation/Testing/Concerns/InteractsWithContainerTest.php
  tests/Foundation/Testing/Concerns/InteractsWithDatabaseTest.php
  tests/Foundation/Testing/Concerns/MakesHttpRequestsTest.php
  tests/Foundation/Testing/DatabaseMigrationsTest.php
  tests/Foundation/Testing/RefreshDatabaseTest.php
  tests/Foundation/fixtures/hyperf/.env
  tests/Foundation/fixtures/routes/test-api.php
  tests/Queue/DatabaseFailedJobProviderTest.php
  tests/Queue/DatabaseUuidFailedJobProviderTest.php
  tests/Queue/PruneBatchesCommandTest.php
  tests/Queue/QueueDatabaseQueueIntegrationTest.php
  tests/Queue/QueueSizeTest.php
  tests/Telescope/FeatureTestCase.php
Labels: feature

#9 Feat: Object Pool Manager
  src/object-pool/composer.json
  src/object-pool/src/Channel.php
  src/object-pool/src/ConfigProvider.php
  src/object-pool/src/ConstantFrequency.php
  src/object-pool/src/Contracts/Factory.php
  src/object-pool/src/Contracts/ObjectPool.php
  src/object-pool/src/Contracts/RecycleStrategy.php
  src/object-pool/src/Contracts/Recycler.php
  src/object-pool/src/Contracts/TimeStrategy.php
  src/object-pool/src/Listeners/StartRecycler.php
  src/object-pool/src/LowFrequencyInterface.php
  src/object-pool/src/ObjectPool.php
  src/object-pool/src/ObjectPoolInterface.php
  src/object-pool/src/ObjectPoolOption.php
  src/object-pool/src/ObjectRecycler.php
  src/object-pool/src/PoolFactory.php
  src/object-pool/src/PoolManager.php
  src/object-pool/src/PoolOption.php
  src/object-pool/src/PoolProxy.php
  src/object-pool/src/SimpleObjectPool.php
  src/object-pool/src/Strategies/TimeStrategy.php
  src/testbench/src/ConfigProviderRegister.php
  tests/Filesystem/FilesystemManagerTest.php
  tests/HttpClient/HttpClientTest.php
  tests/Mail/MailManagerTest.php
  tests/Mail/MailSesTransportTest.php
  tests/Notifications/NotificationChannelManagerTest.php
  tests/ObjectPool/ObjectPoolTest.php
  tests/ObjectPool/ObjectRecyclerTest.php
  tests/ObjectPool/PoolManagerTest.php
  tests/ObjectPool/PoolProxyTest.php
  tests/ObjectPool/TimeStrategyTest.php
  tests/Queue/QueueManagerTest.php
Labels: enhancement

#19 Feat: Implement config:show command
  src/foundation/src/ConfigProvider.php
  src/foundation/src/Console/Commands/ConfigShowCommand.php
Labels: feature

#22 fix: fix type casting for debug property in Environment
  src/support/src/Environment.php
Labels: bug

#23 improve: support customizing path for workbench in testbench-sync
  src/testbench/bin/testbench-sync
Labels: enhancement

#27 fix: Fix issue where different container names resolve to distinct service instances when they should be the same instance
  src/config/src/ConfigProvider.php
  src/config/src/Functions.php
  src/foundation/src/Application.php
  src/http/src/ConfigProvider.php
Labels: bug

#28 feat: implement DataObject in support
  src/support/src/DataObject.php
  tests/Support/DataObjectTest.php
Labels: feature

#37 fix: fix `queue:listen` command
  src/queue/src/Console/ListenCommand.php
Labels: bug

#38 fix: fix depenedencies injection in other queue commands
  src/queue/src/Console/MonitorCommand.php
  src/queue/src/Console/RetryCommand.php
Labels: bug

#34 Feat: support PHP 8.4
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  composer.json
  src/cache/src/LimitedMaxHeap.php
Labels: enhancement

#44 improve: cache resolved definitions in RouteDependency to cover routes with arguments
  src/foundation/src/Application.php
  src/http/src/RouteDependency.php
Labels: enhancement

#45 feat: support explicit bindings in Router
  src/router/src/Middleware/SubstituteBindings.php
  src/router/src/Router.php
Labels: feature

#55 improve: support calling path functions without app container
  src/foundation/src/helpers.php
Labels: enhancement

#63 feat: add coroutine barrier
  src/coroutine/src/Barrier.php
Labels: feature

#66 improve: improve HasPoolProxy trait
  src/object-pool/src/Traits/HasPoolProxy.php
Labels: enhancement

#62 improve: report exceptions in coroutines
  src/coroutine/src/Concurrent.php
  src/coroutine/src/Coroutine.php
Labels: enhancement

#58 feat: use native redis for subscribe/psubscribe calls
  src/core/composer.json
  src/core/src/ConfigProvider.php
  src/core/src/Redis/RedisConnection.php
  src/core/src/Redis/RedisPool.php
  src/core/src/Redis/RedisProxy.php
  src/core/src/Redis/Subscriber.php
  tests/Core/RedisSubscriberTest.php
Labels: enhancement

#67 improve: add type hints for functions in exception handler
  src/foundation/src/Exceptions/Handler.php
Labels: enhancement

#68 feat: implement Hypervel's migration class
  src/core/src/ConfigProvider.php
  src/core/src/Database/Migrations/Migration.php
  src/core/src/Database/Migrations/stubs/blank.stub
  src/core/src/Database/Migrations/stubs/create.stub
  src/core/src/Database/Migrations/stubs/update.stub
  src/devtool/src/Generator/stubs/batches-table.stub
  src/devtool/src/Generator/stubs/failed-jobs-table.stub
  src/devtool/src/Generator/stubs/jobs-table.stub
  src/devtool/src/Generator/stubs/notifications-table.stub
  src/devtool/src/Generator/stubs/sessions-table.stub
  src/telescope/database/migrations/2025_02_08_000000_create_telescope_entries_table.php
  src/testbench/workbench/database/migrations/2023_08_03_000000_create_users_table.php
  tests/Bus/migrations/2024_11_20_000000_create_job_batches_table.php
  tests/Queue/migrations/2024_11_20_000000_create_failed_jobs_table.php
  tests/Queue/migrations/2024_11_20_000000_create_jobs_table.php
Labels: feature
